# # Instructions:
# # Go the bottom of the file and edit the inputs for what you need done
# # You need to copy and paste all the words into the input at the bottom
# # Finally all you need to do is go to
# # --------------------------------------------------------------------
#
# vocabulary_words = ["""abrir,to open,actuar,to act (ú),almorzar,to eat lunch (o-ue),apagar,to put out / to turn off,arreglar,to fix / to tidy,asistir (a),to attend,ayudar,to help,buscar,to look for,caer,to fall (igo),cantar,to sing,celebrar,to celebrate,cenar,to eat dinner,cerrar,to close (e-ie),charlar,to chat,cocinar,to cook,comenzar,to start or begin (e-ie),comer,to eat,comprar,to buy,conducir,to drive (zco),conocer,to know / be familiar with a person or place (zco),construir,to build (y),contar,to count / to tell (o-ue),continuar,to continue (ú),contribuir,to contribute (y),cortar,to cut,crear,to create,creer,to believe,costar,to cost (o-ue),cuidar,to take care of,dar*(le) ... (a alguien),to give ... to someone *(oy),decir,to say / tell (go, e-i),decorar,to decorate,defender,to defend (e-ie),desayunar,to eat breakfast,diseñar,to design,distribuir,to distribute (y),dormir,to sleep (o-ue),empezar,to start / to begin (e-ie),encender,to light (e-ie),encontrar,to find / to find (o-ue),enseñar,to teach,estar,to be (oy/accents),enviar,to send (í),escoger,to pick / to choose (jo),escribir,to write,escuchar,to listen,esquiar,to ski (í),festejar,to celebrate/ to party,ganar,to earn / to win,girar,to spin,gustar(le),to please (someone) / to like,hablar,to talk,hacer,to cook (go),incluir,to include (y),introducir,to introduce (zco),invitar,to invite,ir (a),to go to (irregular),jugar (a),to play (sport / game),limpiar,to clean,llevar,to wear / to carry,llover,to rain (o-ue),mandar,to send,mentir,to lie (e-ie),mirar,to watch,morir,to die (o-ue),nevar,to snow (e-ie),obtener,to get / obtain (go/e-ie),organizar,to organize,pagar,to pay,parecer(le),to seem (to someone) / to think,pasar el rato junto(s),to spend time together,pasar,to pass / to happen,pedir,to ask for (e-i),pensar,to think / plan (e-ie),perder,to lose / to miss (e-ie),platicar,to chat,poder,to be able to / can (o-ue),poner,to put / to place*(go),poner(se),to put on (oneself),preferir,to prefer (e-ie),preparar,to prepare,prestar,to lend,producir,to produce (zco),proteger,to protect (jo),querer,to want (e-ie),recibir,to receive,recoger,to pick up (jo),recordar,to remember (o-ue),repetir,to repeat (e-i),romper,to break,saber,to know (fact/info, how to) (sé),salir,to go out / leave (go),seguir,to follow (go, e-i),servir,to serve (e-i),ser,to be (irregular),tener,to have (go/e-ie),tocar,to play (music) / to touch,tomar,to take,trabajar,to work,traducir,to translate (zoo),traer,to bring / carry (igo),usar,to use,venir,to come (*go, e-ie),vender,to sell,ver,to see (veo),,visitar,to visit,vivir,to live,volar,to fly (o-ue),volver,to return (o-ue),beber,to drink"""]
# vocabulary_words_list = vocabulary_words.split(",")
# terms = vocabulary_words_list[::1]
# definitions = vocabulary_words_list[::2]
# for term in terms:
#     for defintion in definitons
#         print(term + "&" + definition)
